server:
  port: 8080
spring:
  application:
    name: spring-rsocket
  config:
    import:
      - classpath:properties/logback.yml
      - classpath:properties/rsocket.yml
  main:
    banner-mode: console
  mvc:
    view:
      prefix: templates/
      suffix: .html
