# Develop or Default profile
application:
  name: ${rootProject.name}
  version: ${version}
logging:
  level:
    org.springframework.web: info
    io.github.syakuis: trace
server:
  port: 8080
spring:
  config:
    import:
      - classpath:properties/logback.yml
  main:
    banner-mode: console
